#local_backend: true

backend:
  name: git-gateway
  branch: Sommerfest
media_folder: static/images
public_folder: /images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/homepage'
    create: true
    slug: '{{slug}}'
    preview_path: blog/{{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Header Menu Title', name: 'header_menu_title', widget: 'string', required: false }
      - { label: 'Navigation Menu Title', name: 'navigation_menu_title', widget: 'string',required: false }
      - { label: 'Weight', name: 'weight', widget: 'number', required: false  }
      - { label: 'Show in Header Menu', name: 'header_menu', widget: 'boolean', required: false  }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'header'
    label: 'Header'
    folder: 'content/'
    create: true
    slug: '{{slug}}'
    preview_path: header/{{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Header Title', name: 'header_headline', widget: 'string' }
      - { label: 'Header Sub-Title', name: 'header_subheadline', widget: 'string', required: false }
      - { label: 'header_image', name: 'header_image', widget: 'image', required: false }
      - { label: 'header_logo', name: 'header_logo', widget: 'image', required: false }
